apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-libvirt-lab
spec:
  options:
    wait:
      enabled: false
  hosts:
    - role: controller
      ssh:
        address: 192.168.160.10
        user: ubuntu
        keyPath: ~/.ssh/id_rsa

    - role: worker
      ssh:
        address: 192.168.160.11
        user: ubuntu
        keyPath: ~/.ssh/id_rsa

    - role: worker
      ssh:
        address: 192.168.160.12
        user: ubuntu
        keyPath: ~/.ssh/id_ed25519

    - role: worker
      ssh:
        address: 192.168.160.13
        user: ubuntu
        keyPath: ~/.ssh/id_rsa


  k0s:
    version: v1.34.3+k0s.0
    config:
      spec:
        extensions:
          helm:
            concurrencyLevel: 5
            repositories:
              - name: openebs
                url: https://openebs.github.io/openebs
              - name: traefik
                url: https://helm.traefik.io/traefik
              - name: metallb
                url: https://metallb.github.io/metallb

            charts:
              - name: openebs
                chartname: openebs/openebs
                version: "4.1.3"
                namespace: openebs
                order: 1
                values: |
                  engines:
                    local:
                      lvm:
                        # -- Enable/Disable LocalPV LVM Storage Engine
                        enabled: false
                      zfs:
                        # -- Enable/Disable LocalPV ZFS Storage Engine
                        enabled: false
                      rawfile:
                        # Disabled by default since rawfile is not marked as stable yet.
                        # -- Enable/Disable LocalPV Rawfile Storage Engine
                        enabled: false
                    replicated:
                      mayastor:
                        # -- Enable/Disable Replicated PV Mayastor Storage Engine
                        enabled: false
                    loki:
                      # -- Enable/Disable Loki Storage Engine
                      enabled: false    
              
              - name: metallb
                chartname: metallb/metallb
                namespace: metallb
                order: 2

              - name: traefik
                chartname: traefik/traefik
                version: "20.5.3"
                namespace: traefik
                order: 3



        api:
          address: 192.168.160.10
          sans:
            - 192.168.160.10
            - k0s-cp1
        network:
          provider: calico
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
